apiVersion: apps/v1
kind: Deployment 
metadata: #Dictionary
  name: myapp3-deployment
spec: # Dictionary
  replicas: 4
  selector:
    matchLabels:
      app: myapp4
  template:  
    metadata: # Dictionary
      name: myapp4-pod
      labels: # Dictionary
        app: myapp3  # Key value paids
    spec:
      containers: # List
        - name: myapp4-container
          image: stacksimplify/kubenginx:3.0.0
          ports: 
            - containerPort: 80  
    
